PHRASES = {
    "SYSTEMS_ONLINE": "SIH4STUMS AANLAYN.",
    "WELCOME_HOME": "3WEHLXKUM - /HOWM",
    "IDENTIFY": "AYDEHNX4TIX7FAY.",
    "GOOD_MORNING": "GUH4D MOH4RNIHNX.",
    "MONITORING": "MAA4NIXTERIHNX.",
    "YES?": "YEHS?"
}